-- public."user" definition

-- Drop table

-- DROP TABLE public."user";

CREATE TABLE public."user" (
	"index" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id varchar(30) NOT NULL,
	"password" varchar(255) NOT NULL,
	reg_date timestamp DEFAULT now() NULL,
	update_date timestamp DEFAULT now() NULL,
	deleted_at timestamp NULL,
	CONSTRAINT user_id_key UNIQUE (id),
	CONSTRAINT user_pkey PRIMARY KEY (index)
);


-- public.boards definition

-- Drop table

-- DROP TABLE public.boards;

CREATE TABLE public.boards (
	"index" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	title varchar NOT NULL,
	"content" text NOT NULL,
	reg_date timestamp DEFAULT now() NULL,
	update_date timestamp DEFAULT now() NULL,
	user_index int4 NULL,
	deleted_at timestamp NULL,
	total_file_size int8 DEFAULT 0 NULL,
	CONSTRAINT boards_pkey PRIMARY KEY (index),
	CONSTRAINT boards_user_index_fkey FOREIGN KEY (user_index) REFERENCES public."user"("index") ON DELETE CASCADE
);


-- public.files definition

-- Drop table

-- DROP TABLE public.files;

CREATE TABLE public.files (
	"index" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	original_name text NOT NULL,
	stored_name text NOT NULL,
	file_path text NOT NULL,
	file_size int8 NOT NULL,
	reg_date timestamp DEFAULT now() NULL,
	board_index int4 NOT NULL,
	deleted_at timestamp NULL,
	CONSTRAINT files_pkey PRIMARY KEY (index),
	CONSTRAINT fk_files_board_index FOREIGN KEY (board_index) REFERENCES public.boards("index") ON DELETE CASCADE
);